// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mamma_shopping_helper.Data;

#nullable disable

namespace mamma_shopping_helper.Migrations
{
    [DbContext(typeof(MammaDbContext))]
    [Migration("20251208144625_AddDataUltimaModificaAndCreataDa")]
    partial class AddDataUltimaModificaAndCreataDa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("mamma_shopping_helper.Model.ListaDellaSpesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Conclusa")
                        .HasColumnType("bit");

                    b.Property<string>("CreataDa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataUltimaModifica")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descrizione")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Titolo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("DataCreazione");

                    b.ToTable("ListeDellaSpesa");
                });

            modelBuilder.Entity("mamma_shopping_helper.Model.Prodotto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Acquistato")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataAggiunta")
                        .HasColumnType("datetime2");

                    b.Property<int>("ListaDellaSpesaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Quantita")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ListaDellaSpesaId");

                    b.ToTable("Prodotti");
                });

            modelBuilder.Entity("mamma_shopping_helper.Model.Prodotto", b =>
                {
                    b.HasOne("mamma_shopping_helper.Model.ListaDellaSpesa", "ListaDellaSpesa")
                        .WithMany("Prodotti")
                        .HasForeignKey("ListaDellaSpesaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ListaDellaSpesa");
                });

            modelBuilder.Entity("mamma_shopping_helper.Model.ListaDellaSpesa", b =>
                {
                    b.Navigation("Prodotti");
                });
#pragma warning restore 612, 618
        }
    }
}
